apiVersion: v1
entries:
  portworx:
  - apiVersion: v1
    created: "2020-03-22T17:07:50.53278+04:00"
    description: A Helm chart for installing Portworx on Kubernetes.
    digest: 8d591c86d5b98765894730655955c70244efd1140cf4a1b1990e64fa3f1003cd
    home: https://portworx.com/
    icon: https://raw.githubusercontent.com/portworx/helm/master/doc/media/px-logo.png
    name: portworx
    sources:
    - https://github.com/portworx/helm
    urls:
    - https://aayvazyan.github.io/pwx/charts/portworx-1.0.0.tgz
    version: 1.0.0
generated: "2020-03-22T17:07:50.529689+04:00"
